FROM postgres:9.4.4

# add the exported database to the container root
#ADD db-dumps/ /app-db-dumps

# # create demo_schema database
# RUN export DATABASE_URL=postgres://postgres:@postgres:5432/postgres
# RUN export LC_ALL=C.UTF-8
# RUN export POSTGRES_PASSWORD=3x1mpl3

# RUN psql -U postgres
# RUN CREATE DATABASE demo_schema;
# # exit out of postgres
# RUN \q

# copy over the db:
# ---------
# bash into postgres container:
#docker exec -i -t dockernodenginx_postgres_1 bash

# create database:
# RUN export DATABASE_URL=postgres://postgres:@postgres:5432/postgres
# RUN psql -U postgres
# RUN CREATE DATABASE demo_schema;
# RUN \q

# psql -U postgres
# check it:
# \c demo_schema;
# \dt
# exit postgers
# \q
# exit the postgres container
# exit
